[package]
name = "kakoune-toggler"
version = "0.1.0"
authors = ["ABuffSeagull <reecevanatta@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.6"

[dependencies.serde]
version = "1.0.112"
features = [ "derive" ]
